Update order.js
DBCDK/fbi-api-gateway pull request #239
Opened 2023-11-06 14:34 UTC by jonaspraem

2023-11-06 14:50 UTC, kiscdbc requested changes

2023-11-06 14:50 UTC, kiscdbc commented on src/schema/order.js
> +      args.input.forEach(async (input) => {
burde man bruge en Promise.all her=

2023-11-07 08:54 UTC, jonaspraem commented on src/schema/order.js
> +          deleted: false,
.. det er den i submitOrder.. kan ikke sige hvorfor. Det vel bare noget fra openOrder

2023-11-07 10:27 UTC, jonaspraem commented on src/schema/order.js
> +          deleted: false,
Den er ikke med mere, det giver ikke helt mening - Men jeg retter ikke i submitOrder (eksisterende), da jeg ikke kender konsekvenserne.

2023-11-07 10:27 UTC, jonaspraem commented on src/schema/order.js
> +      args.input.forEach(async (input) => {
yes

2023-11-07 10:29 UTC, jonaspraem commented on src/schema/order.js
> +        const submitOrderRes = await context.datasources
Delvist. Vil sige man godt kunne tage alt koden fra `if (context?.profile?.agency == 190101) {` og putte ind i userdata datasourcen.. Ved ikke om der er en grund til det ikke er gjort, men kan lave en lokal funktion

2023-11-07 10:36 UTC, jonaspraem commented on src/schema/order.js
> +          deleted: false,
Kort sagt så er der rigtig mange parametre i submitOrder, som jeg ikke har trukket over i submitMultipleOrders, jeg har kun oprettet dem som jeg kan se jeg skal bruge. Synes det ligner submitOrder trænger til et cleanup - men det må nok vente

2023-11-07 10:45 UTC, kiscdbc commented on src/schema/order.js
> +          deleted: false,
fedt at du testede at det virker uden 👍 
ja, lad os tage submitOrder en anden gang. 
Måske opret en story?

2023-11-07 11:00 UTC, kiscdbc commented on src/schema/order.js
> +        const submitOrderRes = await context.datasources
Tænker det var ikke så vigtigt, når der kun var en submitOrder funktion. Fint at lave en lille hjælper funktion

2023-11-07 11:00 UTC, kiscdbc approved these changes

2023-11-07 11:28 UTC, merged